#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NGI1ZmI0NDRiN2I1Y2Y2ZGFkYzc0MWRkNDZiMGE5NGMzYjBlYjUxM2I5MzQwYTViZjY0MDhlZjZkMjM5MjE1ODIwYmM3N2JiZjNiMzliNjFkZDVjMWI0MWEwYmExMDI3MTZiZA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
